# Generated by Django 5.0.4 on 2024-04-19 20:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alluser',
            name='phone',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='Telephone'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alluser',
            name='name',
            field=models.CharField(max_length=80, verbose_name='Entrer votre nom et prenom'),
        ),
    ]
