# Generated by Django 5.0.4 on 2024-04-20 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alluser_phone_alter_alluser_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alluser',
            name='status',
            field=models.CharField(default='1', max_length=50),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banniere', models.ImageField(upload_to='', verbose_name="Affiche de l'evenement")),
                ('name', models.CharField(max_length=50, verbose_name="Nom de l'evenement")),
                ('date_debut', models.DateTimeField(verbose_name='date de debut')),
                ('description', models.TextField(verbose_name='description')),
                ('is_actived', models.BooleanField(default=True)),
                ('is_free', models.BooleanField(default=False)),
                ('is_normal', models.IntegerField(default=0, verbose_name='Prix normal du ticket')),
                ('is_vip', models.IntegerField(default=0, verbose_name='prix du ticket VIP')),
                ('is_premium', models.IntegerField(default=0, verbose_name='prix du ticket Premium')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
    ]
