# Generated by Django 5.0.4 on 2024-04-20 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_alluser_status_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='place_number',
            field=models.IntegerField(default=0, verbose_name='Nombre de place '),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nom du ticket')),
                ('price', models.IntegerField(verbose_name='Prix du ticket')),
                ('is_actived', models.BooleanField(default=True)),
                ('rang', models.IntegerField(verbose_name='Rang du ticket')),
                ('quantite', models.IntegerField(default=1, verbose_name='Combien de ticket voulez vous ?')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.event')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
            },
        ),
    ]
