# Generated by Django 5.0.4 on 2024-04-20 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_event_place_number_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='is_actived',
        ),
    ]
