# Generated by Django 5.0.4 on 2024-04-21 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_event_banniere'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='rang',
            field=models.IntegerField(verbose_name='phone'),
        ),
    ]
