# Generated by Django 5.0.4 on 2024-04-23 08:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_ticket_rang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='quantite',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Combien de ticket voulez vous ?'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='rang',
            field=models.CharField(max_length=19, verbose_name='phone'),
        ),
    ]
