# Generated by Django 5.0.4 on 2024-04-23 09:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_ticket_quantite_alter_ticket_rang'),
    ]

    operations = [
        migrations.AddField(
            model_name='alluser',
            name='profil',
            field=models.FileField(default=django.utils.timezone.now, upload_to='bannieres/', verbose_name='Image de Profil'),
            preserve_default=False,
        ),
    ]
