# Generated by Django 5.0.4 on 2024-04-23 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alluser_profil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alluser',
            name='profil',
            field=models.FileField(upload_to='Profil/', verbose_name='Image de Profil'),
        ),
    ]
